name: Weekly Cleanup

on:
  schedule:
    - cron: "0 2 * * 0" # Runs at 2 AM every Sunday

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Run cleanup script
        run: echo "Performing weekly cleanup!"